export { default as PlatformDashboardPage } from './PlatformDashboardPage';
export { default as PlatformTenantsPage } from './PlatformTenantsPage';
export { default as PlatformTenantDetailPage } from './PlatformTenantDetailPage';
export { default as PlatformNewTenantPage } from './PlatformNewTenantPage';
export { default as PlatformUsagePage } from './PlatformUsagePage';
export { default as PlatformConfigPage } from './PlatformConfigPage';
export { default as PlatformAgentsPage } from './PlatformAgentsPage';
export { default as PlatformTemplatesPage } from './PlatformTemplatesPage';
export { default as PlatformBrandPage } from './PlatformBrandPage';
